In [1]:
import pandas as pd
import numpy as np

## 영화 - 유저 레이팅 데이터 불러오기

In [2]:
df = pd.read_excel('movies.xlsx')

In [3]:
df

title  userId  rating
0                                        Toy Story (1995)       7     3.0
1                                        Toy Story (1995)       9     4.0
2                                        Toy Story (1995)      13     5.0
3                                        Toy Story (1995)      15     2.0
4                                        Toy Story (1995)      19     3.0
5                                        Toy Story (1995)      20     3.5
6                                        Toy Story (1995)      23     3.0
7                                        Toy Story (1995)      26     5.0
8                                        Toy Story (1995)      30     4.0
9                                        Toy Story (1995)      37     4.0
10                                       Toy Story (1995)      43     4.0
11                                       Toy Story (1995)      44     4.0
12                                       Toy Story (1995)      47     5.0
13                                       Toy Story (1995)      48     4.0
14                                       Toy Story (1995)      55     3.0
15                                       Toy Story (1995)      56     4.0
16                                       Toy Story (1995)      63     5.0
17                                       Toy Story (1995)      67     3.0
18                                       Toy Story (1995)      68     4.0
19                                       Toy Story (1995)      69     5.0
20                                       Toy Story (1995)      70     5.0
21                                       Toy Story (1995)      72     3.5
22                                       Toy Story (1995)      73     5.0
23                                       Toy Story (1995)      75     3.0
24                                       Toy Story (1995)      77     4.0
25                                       Toy Story (1995)      79     2.0
26                                       Toy Story (1995)      84     3.5
27                                       Toy Story (1995)      86     3.0
28                                       Toy Story (1995)      87     3.0
29                                       Toy Story (1995)      89     5.0
...                                                   ...     ...     ...
99972                             Now You See Me 2 (2016)      15     1.0
99973                             Now You See Me 2 (2016)     277     3.0
99974                               The Video Dead (1987)      73     3.0
99975   Teenage Mutant Ninja Turtles: Out of the Shado...      15     2.0
99976           Popstar: Never Stop Never Stopping (2016)      15     1.0
99977                              The Conjuring 2 (2016)      15     4.0
99978                              The Conjuring 2 (2016)      73     3.5
99979                      Approaching the Unknown (2016)      15     0.5
99980                                 Ghostbusters (2016)      15     1.0
99981                         Central Intelligence (2016)      15     2.5
99982                                 Jason Bourne (2016)      62     4.0
99983                                 Jason Bourne (2016)     287     4.5
99984                              The Maid's Room (2014)     624     1.5
99985                         The Legend of Tarzan (2016)      15     1.0
99986                         The Legend of Tarzan (2016)     287     4.0
99987                     The Purge: Election Year (2016)      15     2.0
99988               Mike & Dave Need Wedding Dates (2016)      15     4.0
99989                          Survive and Advance (2013)      56     5.0
99990                                     Tallulah (2016)     547     3.5
99991                                        Piper (2016)     547     4.0
99992                        My Friend Rockefeller (2015)     547     2.5
99993                                    Sunspring (2016)      15     0.5
99994                Kingsglaive: Final Fantasy XV (2016

## Sparse Matrix 형태로 변환

In [4]:
df1 = df.groupby(['title','userId'],as_index = False)['rating'].mean().pivot('title','userId').fillna(0)['rating'].transpose()

In [5]:
df1

title   $9.99 (2008)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                          
1                0.0                                      0.0   
2                0.0                                      0.0   
3                0.0                                      0.0   
4                0.0                                      0.0   
5                0.0                                      0.0   
6                0.0                                      0.0   
7                0.0                                      0.0   
8                0.0                                      0.0   
9                0.0                                      0.0   
10               0.0                                      0.0   
11               0.0                                      0.0   
12               0.0                                      0.0   
13               0.0                                      0.0   
14               0.0                                      0.0   
15               0.0                                      0.0   
16               0.0                                      0.0   
17               0.0                                      0.0   
18               0.0                                      0.0   
19               0.0                                      0.0   
20               0.0                                      0.0   
21               0.0                                      0.0   
22               0.0                                      0.0   
23               0.0                                      0.0   
24               0.0                                      0.0   
25               0.0                                      0.0   
26               0.0                                      0.0   
27               0.0                                      0.0   
28               0.0                                      0.0   
29               0.0                                      0.0   
30               0.0                                      0.0   
...              ...                                      ...   
642              0.0                                      0.0   
643              0.0                                      0.0   
644              0.0                                      0.0   
645              0.0                                      0.0   
646              0.0                                      0.0   
647              0.0                                      0.0   
648              0.0                                      0.0   
649              0.0                                      0.0   
650              0.0                                      0.0   
651              0.0                                      0.0   
652              0.0                                      0.0   
653              0.0                                      0.0   
654              0.0                                      0.0   
655              0.0                                      0.0   
656              0.0                                      0.0   
657              0.0                                      0.0   
658              0.0                                      0.0   
659              0.0                                      0.0   
660              0.0                                      0.0   
661              0.0                                      0.0   
662              0.0                                      0.0   
663              0.0                                      0.0   
664              0.0                                      0.0   
665              0.0                                      0.0   
666              0.0                                      0.0   
667              0.0                                      0.0   
668              0.0                                      0.0   
669              0.0                                      0.0   
670              0.0               

In [6]:
df1.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## KNN 수행

In [8]:
from sklearn.neighbors import NearestNeighbors
neigh = NearestNeighbors(n_neighbors=30)

In [9]:
neigh.fit(df1.values)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=1, n_neighbors=30, p=2, radius=1.0)

## 추천할 user 선택

In [10]:
user = 123

In [11]:
df_user = pd.DataFrame({'title':df1.iloc[user].index,'rating':df1.iloc[user].values})

### 해당 유저가 rating을 남긴(이미 감상 한) 영화 추출

In [12]:
df_user = df_user[df_user.rating != 0]

### 추천 하고자 하는 user와 가장 가까운 user들의 정보를 출력

In [27]:
print(neigh.kneighbors([df1.values[user]])) 

(array([[ 0.        , 34.13942003, 34.96426747, 35.07848343, 35.12477758,
        35.5492616 , 35.57035282, 35.5844067 , 35.93048845, 36.03123645,
        36.23534186, 36.62649314, 36.85105155, 36.93913913, 36.96958209,
        36.98310425, 37.06076092, 37.10121292, 37.11468712, 37.11805491,
        37.131523  , 37.15844453, 37.18870796, 37.22902094, 37.2424489 ,
        37.28605638, 37.38649489, 37.41323295, 37.45997864, 37.46665184]]), array([[123, 115, 424, 428, 346, 447, 457, 409, 378, 578,  78, 585, 169,
        634, 512,  13, 577, 339, 220, 336, 318, 190, 106, 270, 108, 444,
        398, 505, 322, 208]], dtype=int64))


In [29]:
df1

title   $9.99 (2008)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                          
1                0.0                                      0.0   
2                0.0                                      0.0   
3                0.0                                      0.0   
4                0.0                                      0.0   
5                0.0                                      0.0   
6                0.0                                      0.0   
7                0.0                                      0.0   
8                0.0                                      0.0   
9                0.0                                      0.0   
10               0.0                                      0.0   
11               0.0                                      0.0   
12               0.0                                      0.0   
13               0.0                                      0.0   
14               0.0                                      0.0   
15               0.0                                      0.0   
16               0.0                                      0.0   
17               0.0                                      0.0   
18               0.0                                      0.0   
19               0.0                                      0.0   
20               0.0                                      0.0   
21               0.0                                      0.0   
22               0.0                                      0.0   
23               0.0                                      0.0   
24               0.0                                      0.0   
25               0.0                                      0.0   
26               0.0                                      0.0   
27               0.0                                      0.0   
28               0.0                                      0.0   
29               0.0                                      0.0   
30               0.0                                      0.0   
...              ...                                      ...   
642              0.0                                      0.0   
643              0.0                                      0.0   
644              0.0                                      0.0   
645              0.0                                      0.0   
646              0.0                                      0.0   
647              0.0                                      0.0   
648              0.0                                      0.0   
649              0.0                                      0.0   
650              0.0                                      0.0   
651              0.0                                      0.0   
652              0.0                                      0.0   
653              0.0                                      0.0   
654              0.0                                      0.0   
655              0.0                                      0.0   
656              0.0                                      0.0   
657              0.0                                      0.0   
658              0.0                                      0.0   
659              0.0                                      0.0   
660              0.0                                      0.0   
661              0.0                                      0.0   
662              0.0                                      0.0   
663              0.0                                      0.0   
664              0.0                                      0.0   
665              0.0                                      0.0   
666              0.0                                      0.0   
667              0.0                                      0.0   
668              0.0                                      0.0   
669              0.0                                      0.0   
670              0.0               

In [32]:
[df1.values[user]]

[array([0., 0., 0., ..., 0., 0., 0.])]

In [14]:
neigh.kneighbors([df1.values[user]])[1][0]

array([123, 115, 424, 428, 346, 447, 457, 409, 378, 578,  78, 585, 169,
       634, 512,  13, 577, 339, 220, 336, 318, 190, 106, 270, 108, 444,
       398, 505, 322, 208], dtype=int64)

In [15]:
df1.iloc[neigh.kneighbors([df1.values[user]])[1][0]]

title   $9.99 (2008)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                          
124              0.0                                      0.0   
116              0.0                                      0.0   
425              0.0                                      0.0   
429              0.0                                      0.0   
347              0.0                                      0.0   
448              0.0                                      0.0   
458              0.0                                      0.0   
410              0.0                                      0.0   
379              0.0                                      0.0   
579              0.0                                      0.0   
79               0.0                                      0.0   
586              0.0                                      0.0   
170              0.0                                      0.0   
635              0.0                                      0.0   
513              0.0                                      0.0   
14               0.0                                      0.0   
578              0.0                                      0.0   
340              0.0                                      0.0   
221              0.0                                      0.0   
337              0.0                                      0.0   
319              0.0                                      0.0   
191              0.0                                      0.0   
107              0.0                                      0.0   
271              0.0                                      0.0   
109              0.0                                      0.0   
445              0.0                                      0.0   
399              0.0                                      0.0   
506              0.0                                      0.0   
323              0.0                                      0.0   
209              0.0                                      0.0   

title   'Neath the Arizona Skies (1934)  'Round Midnight (1986)  \
userId                                                            
124                                 0.0                     0.0   
116                                 0.0                     0.0   
425                                 0.0                     0.0   
429                                 0.0                     0.0   
347                                 0.0                     0.0   
448                                 0.0                     0.0   
458                                 0.0                     0.0   
410                                 0.0                     0.0   
379                                 0.0                     0.0   
579                                 0.0                     0.0   
79                                  0.0                     0.0   
586                                 0.0                     0.0   
170                                 0.0                     0.0   
635                                 0.0                     0.0   
513                                 0.0                     0.0   
14                                  0.0                     0.0   
578                                 0.0                     0.0   
340                                 0.0                     0.0   
221                                 0.0                     0.0   
337                                 0.0                     0.0   
319                                 0.0                     0.0   
191                                 0.0                     0.0   
107                                 0.0                     0.0   
271                                 0.0                     0.0   
109                                 0.0                     0.0   
445                                 0.0                     0.0   
399                                 0.0    

In [16]:
df_result = pd.DataFrame(df1.iloc[neigh.kneighbors([df1.values[user]])[1][0]].sum())

### 추출된 user들의 영화 별 rating을 모두 더한다

In [17]:
df1.iloc[neigh.kneighbors([df1.values[user]])[1][0]].sum()

title
$9.99 (2008)                                                              0.0
'Hellboy': The Seeds of Creation (2004)                                   0.0
'Neath the Arizona Skies (1934)                                           0.0
'Round Midnight (1986)                                                    0.0
'Salem's Lot (2004)                                                       0.0
'Til There Was You (1997)                                                 0.0
'burbs, The (1989)                                                        0.0
'night Mother (1986)                                                      0.0
(500) Days of Summer (2009)                                               0.0
*batteries not included (1987)                                            0.0
...And God Spoke (1993)                                                   0.0
...And Justice for All (1979)                                             0.0
1-900 (06) (1994)                                         

### 추출된 user들의 영화 별 rating의 개수를 구한다

In [18]:
df1.iloc[neigh.kneighbors([df1.values[user]])[1][0]].astype(bool).sum(axis=0)

title
$9.99 (2008)                                                              0
'Hellboy': The Seeds of Creation (2004)                                   0
'Neath the Arizona Skies (1934)                                           0
'Round Midnight (1986)                                                    0
'Salem's Lot (2004)                                                       0
'Til There Was You (1997)                                                 0
'burbs, The (1989)                                                        0
'night Mother (1986)                                                      0
(500) Days of Summer (2009)                                               0
*batteries not included (1987)                                            0
...And God Spoke (1993)                                                   0
...And Justice for All (1979)                                             0
1-900 (06) (1994)                                                         0
10 (19

In [19]:
np.array(df1.iloc[neigh.kneighbors([df1.values[user]])[1][0]].astype(bool).sum(axis=0).values)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
np.array(df1.iloc[neigh.kneighbors([df1.values[user]])[1][0]].sum().values)

array([0., 0., 0., ..., 0., 0., 0.])

### 영화 별 rating의 합과 영화 별 rating의 개수를 나눈다

In [21]:
pred_rating = np.array(df1.iloc[neigh.kneighbors([df1.values[user]])[1][0]].sum().values)/np.array(df1.iloc[neigh.kneighbors([df1.values[user]])[1][0]].astype(bool).sum(axis=0).values)

C:\Users\dongy\Anaconda3.1\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [22]:
pred_rating

array([nan, nan, nan, ..., nan, nan, nan])

## 추천하고자 하는 user와 비슷한 영화를 관람한 다른 user의 rating을 기반으로 예상 평점 예측

In [23]:
import math
result_title = []
result_rating = []
for i in range(len(pred_rating)):
    if(math.isnan(pred_rating[i]) != True):
        result_title.append(df1.iloc[neigh.kneighbors([df1.values[user]])[1][0]].astype(bool).sum(axis=0).index[i])
        result_rating.append(pred_rating[i])

In [24]:
df_result = pd.DataFrame({'title':result_title,'rating':result_rating}).sort_values(by = 'rating', ascending=False)

In [25]:
df_result

title  rating
189                          Gone with the Wind (1939)    5.00
403                              Shutter Island (2010)    5.00
436                      Star Trek: Generations (1994)    5.00
284                               Mars Attacks! (1996)    5.00
72                        Bourne Ultimatum, The (2007)    5.00
462                                Time Bandits (1981)    5.00
426                                Spider-Man 2 (2004)    5.00
75                                       Brazil (1985)    5.00
36                                Avengers, The (2012)    5.00
17                            American Graffiti (1973)    5.00
152                                    Face/Off (1997)    5.00
435                    Star Trek: First Contact (1996)    5.00
231                                    Iron Man (2008)    5.00
88                                   Casablanca (1942)    5.00
348                                      Psycho (1960)    5.00
239               Joyeux No챘l (Merry Christmas) (2005)    5.00
365                                     Rob Roy (1995)    5.00
174                                Galaxy Quest (1999)    5.00
430                                   Star Trek (2009)    5.00
212                        Hudsucker Proxy, The (1994)    5.00
339                                     Platoon (1986)    4.75
230                             Iron Giant, The (1999)    4.50
181                                   Gladiator (1992)    4.50
266  Lives of Others, The (Das leben der Anderen) (...    4.50
178                                     Gattaca (1997)    4.50
402                                     Shrek 2 (2004)    4.50
477  Twilight Saga: Breaking Dawn - Part 1, The (2011)    4.50
184                     Godfather: Part II, The (1974)    4.50
163                                    Flawless (2007)    4.50
464                       To Kill a Mockingbird (1962)    4.50
..                                                 ...     ...
378                             Rosemary's Baby (1968)    1.00
208                                  Home Alone (1990)    1.00
200  Halloween: The Curse of Michael Myers (Hallowe...    1.00
394                               Sentinel, The (2006)    1.00
498                                      Willow (1988)    0.50
22                            American Tail, An (1986)    0.50
185                     Gods Must Be Crazy, The (1980)    0.50
58                                     Bio-Dome (1996)    0.50
229              Invasion of the Body Snatchers (1956)    0.50
332                           Perfect Murder, A (1998)    0.50
384                                     Sabrina (1995)    0.50
305                              Monster's Ball (2001)    0.50
388                                 Scary Movie (2000)    0.50
296                           Mighty Ducks, The (1992)    0.50
392                         Secret of NIMH, The (1982)    0.50
254                              Legally Blonde (2001)    0.50
237                                   Jerk, The (1979)    0.50
235                                 Jackal, The (1997)    0.50
418                               Space Cowboys (2000)    0.50
60                                  Black Sheep (1996)    0.50
217             I Know What You Did Last Summer (1997)    0.50
216                I Don't Know How She Does It (2011)    0.50
199                            Grumpier Old Men (1995)    0.50
195                           Great Escape, The (1963)    0.50
354                  Rambo: First Blood Part II (1985)    0.50
177                                Garden State (2004)    0.50
159                           Final Destination (2000)    0.50
145  Englishman Who Went Up a Hill But Came Down a ...    0.50
67                                  Boiler Room (2000)    0.50
506                                   Zoolander (2001)    0.50

[507 rows x 2 columns]

## 추천하고자 하는 user가 이미 관람한 영화 제거

In [26]:
df_result[~df_result['title'].isin(df_user['title'])]

title  rating
189                          Gone with the Wind (1939)     5.0
403                              Shutter Island (2010)     5.0
436                      Star Trek: Generations (1994)     5.0
284                               Mars Attacks! (1996)     5.0
72                        Bourne Ultimatum, The (2007)     5.0
462                                Time Bandits (1981)     5.0
426                                Spider-Man 2 (2004)     5.0
75                                       Brazil (1985)     5.0
36                                Avengers, The (2012)     5.0
17                            American Graffiti (1973)     5.0
152                                    Face/Off (1997)     5.0
435                    Star Trek: First Contact (1996)     5.0
231                                    Iron Man (2008)     5.0
88                                   Casablanca (1942)     5.0
348                                      Psycho (1960)     5.0
239               Joyeux No챘l (Merry Christmas) (2005)     5.0
365                                     Rob Roy (1995)     5.0
174                                Galaxy Quest (1999)     5.0
430                                   Star Trek (2009)     5.0
212                        Hudsucker Proxy, The (1994)     5.0
230                             Iron Giant, The (1999)     4.5
266  Lives of Others, The (Das leben der Anderen) (...     4.5
178                                     Gattaca (1997)     4.5
477  Twilight Saga: Breaking Dawn - Part 1, The (2011)     4.5
184                     Godfather: Part II, The (1974)     4.5
163                                    Flawless (2007)     4.5
464                       To Kill a Mockingbird (1962)     4.5
224                                Insider, The (1999)     4.5
387                                    Scarface (1983)     4.5
443  Star Wars: Episode VII - The Force Awakens (2015)     4.5
..                                                 ...     ...
378                             Rosemary's Baby (1968)     1.0
208                                  Home Alone (1990)     1.0
200  Halloween: The Curse of Michael Myers (Hallowe...     1.0
394                               Sentinel, The (2006)     1.0
498                                      Willow (1988)     0.5
22                            American Tail, An (1986)     0.5
185                     Gods Must Be Crazy, The (1980)     0.5
58                                     Bio-Dome (1996)     0.5
229              Invasion of the Body Snatchers (1956)     0.5
332                           Perfect Murder, A (1998)     0.5
384                                     Sabrina (1995)     0.5
305                              Monster's Ball (2001)     0.5
388                                 Scary Movie (2000)     0.5
296                           Mighty Ducks, The (1992)     0.5
392                         Secret of NIMH, The (1982)     0.5
254                              Legally Blonde (2001)     0.5
237                                   Jerk, The (1979)     0.5
235                                 Jackal, The (1997)     0.5
418                               Space Cowboys (2000)     0.5
60                                  Black Sheep (1996)     0.5
217             I Know What You Did Last Summer (1997)     0.5
216                I Don't Know How She Does It (2011)     0.5
199                            Grumpier Old Men (1995)     0.5
195                           Great Escape, The (1963)     0.5
354                  Rambo: First Blood Part II (1985)     0.5
177                                Garden State (2004)     0.5
159                           Final Destination (2000)     0.5
145  Englishman Who Went Up a Hill But Came Down a ...     0.5
67                                  Boiler Room (2000)     0.5
506                                   Zoolander (2001)     0.5

[422 rows x 2 columns]